### ISSUE TITLE
Extension not running

### ISSUE THREAD

**Issue by Horray** [mikaeljorhult/brackets-php-code-quality-tools#24]
Hey there! I have wamp installed on my computer. (Windows 10) I tried installing your extension, but it didn't do anything. Then when I wen to View > PHP Code Quality Tools, it said the extension can't run because php isn't on the machine.

What can I do to fix it?

**Comment by EridianBrian** [comment]
Hey Horray,

You need to set the environment path in windows to set the path to your php installation.
In order to do this:

Right click Start Button and select 'System'
Go to 'Advanced System Settings'
At the bottom of this window select 'Environment Variables'
In 'System variables' find the Variable 'path' and click edit
go to the end of the value string and type ;C:\path\to\php (e.g. ;C:\php)
ENSURE you use the semicolon to separate the values.

Next time you load windows/environment you will have access to the path, if you want it sooner:
copy the entire Path Variable value and open PowerShell (as admin). You can do this by right clicking the start button again.

enter: $env:Path = "<PASTE YOUR COPIED TEXT>";

Reload brackets, and viola!

**Comment by mikaeljorhult** [comment]
Thank you @EridianBrian! That's exactly right.
